services:
  - type: web
    name: dupr-predictor-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd /opt/render/project/src && gunicorn api.app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
